# Default experiment configuration for penguins classification

seed: 42

paths:
  raw: "data/raw"
  interim: "data/interim"
  processed: "data/processed"
  processed_dir: "data/processed"
  model_dir: "models"
  metrics_dir: "models/metrics"

features:
  numeric_features:
    - "bill_length_mm"
    - "bill_depth_mm"
    - "flipper_length_mm"
    - "body_mass_g"
    - "year"
  categorical_features:
    - "island"
    - "sex"
  target: "species"
  test_size: 0.2
  stratify: true

model:
  name: "RandomForestClassifier"
  params:
    n_estimators: 100
    random_state: 42
    max_depth: 10
    min_samples_split: 5
    min_samples_leaf: 2
  tune:
    grid:
      - n_estimators: [50, 100, 200]
        max_depth: [5, 10, 15, null]
        min_samples_split: [2, 5, 10]
        min_samples_leaf: [1, 2, 4]
    cv: 5
    scoring: "accuracy"
    n_jobs: -1