api:
  host: "0.0.0.0"
  port: 8000
  reload: false
  workers: 1

logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}"
  rotation: "1 day"
  retention: "30 days"
  log_file: "logs/app.log"

model_path: "models/latest"